<a href="https://colab.research.google.com/github/Dankort/lab-revisiting-machine-learning/blob/master/Revisiting_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import getpass
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import Normalizer, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import OneHotEncoder

df = pd.read_csv ("/content/learningSet.csv")
df.head()

<ipython-input-38-08e8df435867>:14: DtypeWarning: Columns (4,8,15,42) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv ("/content/learningSet.csv")

,ODATEDW,OSOURCE,TCODE,STATE,ZIP,MAILCODE,PVASTATE,DOB,NOEXCH,RECINHSE,...,TARGET_D,HPHONE_D,RFA_2R,RFA_2F,RFA_2A,MDMAUD_R,MDMAUD_F,MDMAUD_A,CLUSTER2,GEOCODE2
0,8901,GRI,0,IL,61081,,,3712,0,,...,0.0,0.0,L,4.0,E,X,X,X,39.0,C
1,9401,BOA,1,CA,91326,,,5202,0,,...,0.0,0.0,L,2.0,G,X,X,X,1.0,A
2,9001,AMH,1,NC,27017,,,0,0,,...,0.0,1.0,L,4.0,E,X,X,X,60.0,C
3,8701,BRY,0,CA,95953,,,2801,0,,...,0.0,1.0,L,4.0,E,X,X,X,41.0,C
4,8601,,0,FL,33176,,,2001,0,X,...,0.0,1.0,L,2.0,F,X,X,X,26.0,A

In [39]:
df.shape

(10243, 481)

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10243 entries, 0 to 10242
Columns: 481 entries, ODATEDW to GEOCODE2
dtypes: float64(395), int64(12), object(74)
memory usage: 37.6+ MB

In [41]:
df.dtypes

ODATEDW       int64
OSOURCE      object
TCODE         int64
STATE        object
ZIP          object
             ...
MDMAUD_R     object
MDMAUD_F     object
MDMAUD_A     object
CLUSTER2    float64
GEOCODE2     object
Length: 481, dtype: object

In [42]:
round(df.describe())

,ODATEDW,TCODE,DOB,AGE,NUMCHLD,INCOME,WEALTH1,HIT,MBCRAFT,MBGARDEN,...,FISTDATE,NEXTDATE,TIMELAG,AVGGIFT,CONTROLN,TARGET_B,TARGET_D,HPHONE_D,RFA_2F,CLUSTER2
count,10243.0,10243.0,10243.0,7728.0,1345.0,8002.0,5499.0,10243.0,4605.0,4605.0,...,10242.0,9181.0,9181.0,10242.0,10242.0,10242.0,10242.0,10242.0,10242.0,10231.0
mean,9140.0,51.0,2723.0,62.0,2.0,4.0,5.0,3.0,0.0,0.0,...,9134.0,9150.0,8.0,13.0,95861.0,0.0,1.0,1.0,2.0,32.0
std,343.0,1039.0,2127.0,17.0,1.0,2.0,3.0,9.0,0.0,0.0,...,318.0,295.0,6.0,8.0,55235.0,0.0,4.0,0.0,1.0,19.0
min,8601.0,0.0,0.0,13.0,1.0,1.0,0.0,0.0,0.0,0.0,...,7211.0,7211.0,0.0,2.0,27.0,0.0,0.0,0.0,1.0,1.0
25%,8801.0,0.0,212.0,48.0,1.0,2.0,3.0,0.0,0.0,0.0,...,8810.0,8903.0,4.0,8.0,48157.0,0.0,0.0,0.0,1.0,15.0
50%,9201.0,1.0,2607.0,62.0,1.0,4.0,6.0,0.0,0.0,0.0,...,9201.0,9204.0,6.0,12.0,95606.0,0.0,0.0,1.0,1.0,32.0
75%,9501.0,2.0,4601.0,76.0,2.0,5.0,8.0,3.0,0.0,0.0,...,9409.0,9409.0,11.0,15.0,144246.0,0.0,0.0,1.0,3.0,49.0
max,9701.0,72002.0,8408.0,98.0,5.0,7.0,9.0,240.0,6.0,3.0,...,9603.0,9702.0,90.0,216.0,191763.0,1.0,100.0,1.0,4.0,62.0

# Checking for nulls and Nans values in all the columns

In [43]:
#checking for missing values and NANS.
print(df.isnull().sum())

ODATEDW      0
OSOURCE      0
TCODE        0
STATE        0
ZIP          0
            ..
MDMAUD_R     1
MDMAUD_F     1
MDMAUD_A     1
CLUSTER2    12
GEOCODE2    12
Length: 481, dtype: int64

#Exclude the following variables by looking at the definitions. Create a new empty list called drop_list. We will append this list and then drop all the columns in this list later:

In [44]:
df = df.drop(['OSOURCE','ZIP'], axis=1)

In [45]:
#Create a new empty list called drop_list.
drop_list = []

# Append column names to the drop_list as needed
drop_list.append('OSOURCE')
drop_list.append('ZIP CODE')

# Print the current contents of drop_list
print("Current drop_list:", drop_list)

Current drop_list: ['OSOURCE', 'ZIP CODE']

In [46]:
df.columns

Index(['ODATEDW', 'TCODE', 'STATE', 'MAILCODE', 'PVASTATE', 'DOB', 'NOEXCH',
       'RECINHSE', 'RECP3', 'RECPGVG',
       ...
       'TARGET_D', 'HPHONE_D', 'RFA_2R', 'RFA_2F', 'RFA_2A', 'MDMAUD_R',
       'MDMAUD_F', 'MDMAUD_A', 'CLUSTER2', 'GEOCODE2'],
      dtype='object', length=479)

# Identify columns that over 85% missing values

In [47]:
# Calculate the percentage of missing values for each column
missing_percentage = (df.isnull().sum() / len(df)) * 100

# Create a list of column names with more than 85% missing values
columns_to_drop = missing_percentage[missing_percentage > 85].index.tolist()

# Print or handle the identified columns
print("Columns with over 85% missing values:", columns_to_drop)

Columns with over 85% missing values: ['NUMCHLD', 'RDATE_3', 'RDATE_4', 'RDATE_5', 'RDATE_6', 'RDATE_7', 'RDATE_10', 'RDATE_13', 'RDATE_15', 'RDATE_17', 'RDATE_20', 'RDATE_21', 'RDATE_23', 'RAMNT_3', 'RAMNT_4', 'RAMNT_5', 'RAMNT_6', 'RAMNT_7', 'RAMNT_10', 'RAMNT_13', 'RAMNT_15', 'RAMNT_17', 'RAMNT_20', 'RAMNT_21', 'RAMNT_23']

# Remove those columns from the dataframe

In [48]:
# Dropping the identified columns from the DataFrame.
df = df.drop(columns=columns_to_drop)

#Reduce the number of categories in the column GENDER. The column should only have either "M" for males, "F" for females, and "other" for all the rest

In [54]:
# Display unique values in the "GENDER" column before modification
print("Unique values before modification:", df['GENDER'].unique())

# Map values to the desired categories
gender_mapping = {'M': 'M', 'F': 'F', 'other': 'other'}

# Replace values not in the mapping with 'other'
df['GENDER'] = df['GENDER'].map(gender_mapping).fillna('other')

# Display unique values in the "GENDER" column after modification
print("Unique values after modification:", df['GENDER'].unique())

Unique values before modification: ['F' 'M' 'other']
Unique values after modification: ['F' 'M' 'other']

In [55]:
print(df['GENDER'].value_counts())

F        5470
M        4263
other     510
Name: GENDER, dtype: int64